### PR TITLE
Prepare open source

### LINKED ISSUE #8: Prepare Repo for Open Source
The following checklist gives a comprehensive action items that should be taken before making the repository public. 

- [x]  Repository info
    - [x]  Add repo description
    - [x]  Update website to flow.com
    - [x]  Add relevant repository tags (i.e. `blockchain` `js`, etc)
- [ ]  General security audit
    - [ ]  Searching for references to internal IP (look into ways to automate search)
    - [ ]  Remove secrets
    - [ ]  Remove any mentions of NBA, Moments, USDT, Circle, any other partner names
- [ ]  Define merge workflow
    - [ ]  Branch rules:
        - [ ]  `main`
            - [ ]  **Require pull request reviews before merging (1 approving review)**
                - [ ]  **Require review from Code Owners**
            - [ ]  **Require status checks to pass before merging**
                - [ ]  **Require branches to be up to date before merging**
            - [ ]  **Require linear history**
            - [ ]   **Restrict who can push to matching branches**
                - [ ]  Choose `onflow/flow` team

- [ ]  Add necessary team members, adjust access levels
    - [ ]  `onflow/flow-admin` ⇒ Admin access
    - [ ]  `onflow/flow` ⇒ Write access

The following changes should be made in a **new branch** (i.e. `onflow-migration`) and merged into `main` as a PR. Example: [https://github.com/onflow/flow/pull/1](https://github.com/onflow/flow/pull/1)

- [ ]  Code cleanup
    - [ ]  Update `Makefile`/ `package.json` with relevant commands (i.e. `test` `start` `build`)
    - [ ]  Clean up comments
    - [ ]  Remove unnecessary TODOs
    - [ ]  **THIS IS YOUR CHANCE TO MAKE YOUR CODE PRETTY**
- [x]  Add `CODEOWNERS` file
    - [x]  *Even if repo isn't split into sections for different owners, add at least one owner for the entire repo*
- [x]  Add contribution guidelines & code of conduct:
    - [x]  Contribution guidelines: https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md
    - [x]  Code of conduct: https://github.com/onflow/flow-nft/blob/master/CODE_OF_CONDUCT.md
    - [x] Responsible Disclosure Language[https://github.com/dapperlabs/flow/pull/14/files](https://github.com/dapperlabs/flow/pull/14/files)
- [x]  Add license and copyright notice:
    - [x]  License: https://github.com/onflow/flow-nft/blob/master/LICENSE
- [x]  Add issue and PR templates:
    - Issue templates:
        - [x]  Bug report: https://github.com/onflow/flow-nft/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
        - [x]  Feature request: https://github.com/onflow/flow-NFT/blob/master/.github/ISSUE_TEMPLATE/feature-request.md
    - PR template

### PR DESCRIPTION
**Pull request by gus-labs**
Closes: #8

## Description

Add guidelines documents for the open sourcing of this repository.

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-nft/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by alilloig** [comment]
@gus-labs files look good, did you do the stuff on this list? https://github.com/onflow/fcl-contracts/issues/8

Branch rules and permissions, I checked the ones I'm aware that are done

**Comment by gus-labs** [comment]
> @gus-labs files look good, did you do the stuff on this list? #8
> 
> Branch rules and permissions, I checked the ones I'm aware that are done

Yes, I did. I was given repo admin rights two days ago.

**Comment by alilloig** [comment]
> Yes, I did. I was given repo admin rights two days ago.

awesome, then I believe we are good to go!

**Review by alilloig — APPROVED** [review]
lgtm

**Pull request merged**
